---
  metaData: 
    author: "d3fkon"
    git-repo: "https://github.com/d3fkon/repo_af"
    approval: 
      approved-by: "d3fkon"
      approval-date: 1564170517100
  job: 
    job-name: "d3fkonxrepo_af"
    config: 
      pre-unit-test: "yes"
      post-unit-test: "no"
      dev: "no"
